dataUrl: "https://raw.githubusercontent.com/RHRolun/automl-loan/main/cleaned_loan_data.csv"
schedule: "0 19 * * *"
workbenchImage: "registry.redhat.io/rhoai/odh-workbench-codeserver-datascience-cpu-py312-rhel9:v3.3"
