dataUrl: "https://github.com/RHRolun/automl-loan/blob/main/cleaned_loan_data.csv"  # URL to download and upload as the training data file
schedule: "0 19 * * *"  # cron schedule for the pipeline run (default: daily at 7pm)
